# Generated by Django 5.0.2 on 2025-04-05 15:57

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_table_restaurant_alter_booking_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
