# Generated by Django 5.0.2 on 2025-04-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
